# Generated by Django 4.2.3 on 2023-07-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sug', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catageory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
    ]
